/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controler.LoginController;


/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        setSize(658,460);
        setVisible(true);
        pasta.setOpaque(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pasta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        msn_nombre = new javax.swing.JLabel();
        msn_correo = new javax.swing.JLabel();
        tx_correo = new javax.swing.JTextField();
        msn_pass = new javax.swing.JLabel();
        tx_pass = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        msn_ERROR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pasta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/imagen1.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        msn_nombre.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        msn_nombre.setForeground(new java.awt.Color(0, 51, 204));
        msn_nombre.setText("Plataforma EduCol");

        msn_correo.setText("Correo:");

        tx_correo.setBackground(new java.awt.Color(153, 204, 255));

        msn_pass.setText("Contraseña:");

        tx_pass.setBackground(new java.awt.Color(153, 204, 255));

        btn_ingresar.setBackground(new java.awt.Color(153, 204, 255));
        btn_ingresar.setText("Iniciar Sesion");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pastaLayout = new javax.swing.GroupLayout(pasta);
        pasta.setLayout(pastaLayout);
        pastaLayout.setHorizontalGroup(
            pastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pastaLayout.createSequentialGroup()
                .addGroup(pastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pastaLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(msn_correo)))
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(pastaLayout.createSequentialGroup()
                .addGroup(pastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pastaLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(msn_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pastaLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(msn_pass))
                    .addGroup(pastaLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(pastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pastaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btn_ingresar))
                            .addComponent(msn_ERROR))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pastaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );
        pastaLayout.setVerticalGroup(
            pastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pastaLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msn_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msn_correo)
                .addGap(9, 9, 9)
                .addComponent(tx_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msn_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msn_ERROR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ingresar)
                .addGap(28, 28, 28))
        );

        getContentPane().add(pasta);
        pasta.setBounds(80, 50, 440, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/OF18H90.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 620, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:
      LoginController loginController = new LoginController();
      String correo = tx_correo.getText();
     String contraseña = tx_pass.getText(); 


       loginController.iniciarSesion(correo, contraseña, this);

        
    }//GEN-LAST:event_btn_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel msn_ERROR;
    private javax.swing.JLabel msn_correo;
    private javax.swing.JLabel msn_nombre;
    private javax.swing.JLabel msn_pass;
    private javax.swing.JPanel pasta;
    private javax.swing.JTextField tx_correo;
    private javax.swing.JTextField tx_pass;
    // End of variables declaration//GEN-END:variables
}
